### PR TITLE
Exit process as soon as CLI finishes

### PR DESCRIPTION
**Pull request by lbguilherme**
Workaround for https://github.com/brianc/node-postgres/issues/2907.

Currently on a Postgres database that doesn't have SSL enabled, kysely-codegen will first attempt to connect with SSL, fail, and then proceed to connect without SSL. After that it finished successfully, but it hangs before exiting before some TCP connection from the SSL attempt is still open.

After the CLI finishes successfully, let's just close the process. This saves a few annoying seconds for me.

### CODE REVIEW

**Comment by RobinBlomberg** [comment]
Interesting! Two questions:
1. Could this cause any unwanted side effects, such as keeping a database connection open on exit?
2. Is it not possible to gracefully exit the connections instead, eliminating the need for `process.exit(0)`?

If the answer to both is "no", I guess it may be merged, if it works as expected on my machine as well.

**Comment by lbguilherme** [comment]
1. No. `process.exit` will exit the current process and immediately free all of its resources, such as memory and open files/sockets. As this is a CLI and the job is already done at this point, there is no harm.
2. pg.connect() throws and the object we could close is leaked. I sent a patch upstream fixing this, but it could take a while (https://github.com/brianc/node-postgres/pull/2908). Alternatively we could have a `--ssl` flag instead of blindly trying connect with or without ssl, but that would be a breaking change. Just to be clear, I'm talking about this functionhttps://github.com/RobinBlomberg/kysely-codegen/blob/master/src/introspector.ts#L28.

This change is not pretty, but is harmless.

**Comment by RobinBlomberg** [comment]
Great points! Then this will likely be migrated.

Some SSL support will probably be implemented seperately as well, as requested in #36.

**Comment by RobinBlomberg** [comment]
Released in `kysely-codegen@0.10.0`!

**Pull request merged**
