### PR TITLE
Support PostgreSQL scalar arrays

### PR DESCRIPTION
**Pull request by johynpapin**
Hello,

First of all, thank you very much for this great project!

I use arrays like `TEXT[]` in my PostgreSQL schema. This PR aims to add support for these arrays in `kysely-codegen`.

Don't hesitate to tell me if I did it wrong, I will make the necessary changes. My biggest doubt is about `ArrayExpressionNode`, should I use it instead of adding `ArrayNode`?

I formatted the `src` folder using Prettier. This PR adds array support only for the PostgreSQL dialect.

Thank you in advance!

### CODE REVIEW

**Comment by RobinBlomberg** [comment]
Hello! Interesting. The `ArrayExpressionNode` should indeed be right fit for your use case.

Do array types start with `_`? Haven't encountered this.

**Comment by johynpapin** [comment]
Hello ! Thank you for this answer, I will make the change.

Yes indeed, PostgreSQL adds a `_` in front of the type name to indicate that it is an array, I find that surprising too. For example, `TEXT[]` will give `_text`.

**Comment by johynpapin** [comment]
It's done, it's actually much better this way.

**Comment by johynpapin** [comment]
Here is StackOverflow topic discussing the `_` in PostgreSQL: https://stackoverflow.com/questions/71332976/text-postgres-data-type

**Comment by RobinBlomberg** [comment]
Very nice! I will test and merge this as soon as I have some time over. 🙌

**Comment by johynpapin** [comment]
Awesome, thanks a lot! I haven't written any tests, but if you want I can try to add some.

**Comment by RobinBlomberg** [comment]
Implemented (with some modifications) in `kysely-codegen@0.8.0`! Thank you.

**Pull request closed without merging**
