### PR TITLE
add Planetscale

### PR DESCRIPTION
**Pull request by harisraharjo**
this pull request is for issue number #57 

I added tsup because currently `@planetscale/database` and [kysely-planetscale](https://github.com/depot/kysely-planetscale) only support esmodule. and I don't know how to use tsc.
Sorry I didn't test it because I was in a hurry and also I got this error `Cannot use import statement outside a module` when I tried to test it. But I got it working. 
This is not perfect but I hope it helps 

-edit
adding test for planetscale is not going to work because of this [ts-node-dev's issue](https://github.com/wclr/ts-node-dev/issues/265) which is related to esm.

### CODE REVIEW

**Comment by harisraharjo** [comment]
it turns out `Cannot use import statement outside a module` is because I changed the tsconfig settings to esnext, so I revert it back

**Comment by RobinBlomberg** [comment]
Code looks nice, but I guess one question is whether this should be part of `kysely-codegen`, or if we should make it easy to add custom plugins. Considering that `kysely-planetscale` is a custom dialect and that it's probably not a scalable solution to include every possible dialect in the core, I am leaning towards the latter option.

That means we'll need to focus on making a (minimal) plugin system viable though.

**Comment by harisraharjo** [comment]
Yes you are right.. maybe we could also make the official dialects (mysql & postgres) as a "plugin" as well instead of specifying `--dialect`

**Comment by RobinBlomberg** [comment]
Not unreasonable, but I think `mysql`/`postgres`/`sqlite` might continue to be part of the core as long as they are in the [kysely core](https://github.com/koskimas/kysely/tree/master/src/dialect) (and for the sake of making it easy for most users to start). But who knows in the future.

But at the very least, custom plugins should become a breeze to use.

**Pull request closed without merging**
