### PR TITLE
Added support for bun:sqlite

### PR DESCRIPTION
**Pull request by KaruroChori**
Added bun-sqlite based on `kysely-bun-worker`
This is needed, as the driver for bun is not compatible out of the box.

### CODE REVIEW

**Comment by RobinBlomberg** [comment]
Thanks! Added!

**Comment by EspadaV8** [comment]
This is stopping installation of 0.12 with Kysely 0.27. `kysely-bun-worker` has a peer dependency on Kysely `^0.26`

**Comment by KaruroChori** [comment]
Issue confirmed. Kysely got a new "major" release 10 days ago, and kysely-bun-worker was not bumped.

**Comment by KaruroChori** [comment]
I opened https://github.com/subframe7536/kysely-sqlite-tools/issues/6.
For now I think it would be better to revert this PR to ensure people can use the new version.

**Comment by EspadaV8** [comment]
If you don't want to revert it, I added in the following `overrides` into `packages.json` (as hinted at in https://github.com/subframe7536/kysely-sqlite-tools/issues/6) and things seem to install fine

```json
    "overrides": {
        "kysely-bun-worker": {
            "kysely": "^0.27"
        }
    }
````

**Comment by RobinBlomberg** [comment]
Thanks for the heads up.

I set `0.11.0` as the latest version now, but `0.12.0` can still be used for those who want the latest changes. I'll release `0.12.1` once the other package makes a new release.

**Pull request merged**
