### PR TITLE
 feat: add `--ignore-pattern` CLI option

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Hey! This PR adds a new CLI option, `--ignore-pattern`, that allows users to ignore tables that match the pattern. For example:

```sh
# Ignore specific tables
kysely-codegen --ignore-pattern '^(secret_table|another_secret_table)$'

# Ignore table names starting with "_"
kysely-codegen --ignore-pattern '^_'
```

My particular use-case is I have auto-generated tables whose names start with an underscore. Currently when I run `kysely-codegen`, I need to then manually edit the generated file to remove whatever temporary tables existed at the time. With a CLI flag like this, I can ignore those tables and skip the manual edit step.

If you like this idea, let me know if the name works for you, I'm happy to adjust anything!

### CODE REVIEW

**Comment by RobinBlomberg** [comment]
Very nice! 🚀 I will like merge this into the next release.

**Comment by ledburyb** [comment]
I'm looking for very similar functionality only I'd like to be able to ignore tables by schema instead.
Would it make sense to extend this to have the exclusion pattern be `(<schema>.<pattern>)` to support both cases?

**Comment by jacobwgillespie** [comment]
@ledburyb interesting - are you trying to ignore the entire schema, or just specific tables within specific schemas?

**Comment by ledburyb** [comment]
For this specific case I'm using CockroachDB in a project and it has a `crdb_internal` schema with a lot of tables I'd never want to touch from application code. The Kysely introspector seems to filter out most of the Postgres internal tables but not CockroachDB ones.

Also in a larger project I would often use schemas to silo off autogenerated tables in a similar way that you're using the `_` prefix.

For the --ignore-pattern syntax I'd probably want to do something like:
`--ignore-pattern '^crdb_internal.*$'`

**Comment by ledburyb** [comment]
Alternatively it could just be a separate `--ignore-schema` flag.

**Comment by jacobwgillespie** [comment]
Ah, interesting, Kysely's introspector by default introspects all schemas, and performs the filtering in that query: 

https://github.com/koskimas/kysely/blob/f1feeb32c3d6cd4553db1ca9857ac8508858e5ab/src/dialect/postgres/postgres-introspector.ts#L62-L63

@RobinBlomberg would you be interested in this PR implementing two options, `--ignore-tables` and `--ignore-schemas`, for filtering out one or the other?

It wouldn't solve the use-case of wanting to exclude two tables with different schemas but identical names (e.g., exclude `private.users` but allow `private.something` and `public.users`). But that feels like a less-common use-case, and there's other workarounds for it I think (like generating two typedefs).

**Comment by jacobwgillespie** [comment]
I've implemented `--ignore-schemas` and `--ignore-tables`, let me know if you'd like me to modify this in any way 👍

**Comment by RobinBlomberg** [comment]
Valid ideas. I'm thinking that it's necessary to be able to ignore specific schema/table combinations, such as `schema.table`, so maybe they shouldn't be two separate options.

It may also be confusing that the pattern is a RegExp, which makes `.` above match any character, meaning that `schemaxtable` would match. Maybe glob patterns would be better? For example:

- `users`
- `information_schema.*`
- `*_events`

**Comment by RobinBlomberg** [comment]
I'm thinking about using [globby](https://www.npmjs.com/package/globby) to support:

- Wildcards: `public.*` (`**` would be the same since we don't have `/` folder separators)
- Any character: `data_?` (matches `data_0`)
- "OR" expressions: `user_{events|settings}` (matches `user_events` and `user_settings`)
- Negations: `public.*,!public.users` (only matches the `users` table)

**Comment by ledburyb** [comment]
@RobinBlomberg - Sounds good to me.

**Comment by jacobwgillespie** [comment]
Nice, I've reverted back to just `--ignore-pattern` and implemented glob matching (with `micromatch`, which is what `globby` uses). It matches against `schema.table`, so that should support all the combinations of options.

**Comment by RobinBlomberg** [comment]
Incredible! I'll look into merging this shortly.

**Comment by RobinBlomberg** [comment]
Merged and released in `kysely-codegen@^0.6.2`.

I made some additional changes though:
- It's possible to match simple patterns like `users` (patterns that don't contain a `.`)
- Renamed `--ignore-pattern` to `--exclude-pattern` (see below)
- Added `--include-pattern`
- Added a `TableMatcher` class with some tests

**Comment by jacobwgillespie** [comment]
Awesome, thank you so much @RobinBlomberg! 🎉

**Pull request merged**
